services:
  frontend:
    build: ./FrontEnd
    ports:
      - "5173:5173"
    environment:
      VITE_COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
  backend:
    build: ./BackEnd
    ports:
      - "3000:3000"
    environment:
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      COGNITO_POOL_ID: ${COGNITO_POOL_ID}
      CONNECTION_STRING: "postgresql://postgres_user:postgres_password@database:5432/postgres_db"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 1m
      timeout: 5s
      start_period: 10s
      start_interval: 1s